/**
 * Regenerates FEATURES.md from lib/features/registry.ts.
 *
 * Run with `npm run docs:features` after changing the registry. Do not
 * hand-edit FEATURES.md — it's generated and will be overwritten.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { FEATURE_CATEGORIES, countByStatus, type FeatureStatus } from "../lib/features/registry.ts";

const STATUS_MARK: Record<FeatureStatus, string> = {
  shipped: "x",
  beta: "~",
  planned: " ",
};

const STATUS_LABEL: Record<FeatureStatus, string> = {
  shipped: "Shipped",
  beta: "Beta",
  planned: "Planned",
};

function render(): string {
  const counts = countByStatus();
  const lines: string[] = [];

  lines.push("# Feature Checklist");
  lines.push("");
  lines.push(
    "> Generated from `lib/features/registry.ts` by `npm run docs:features`. Do not edit this file directly — edit the registry and regenerate. The same registry powers the live admin view at `/admin/features`."
  );
  lines.push("");
  lines.push(
    `**${counts.shipped} shipped · ${counts.beta} in beta · ${counts.planned} planned.**`
  );
  lines.push("");
  lines.push("`[x]` shipped · `[~]` beta / in progress · `[ ]` planned");
  lines.push("");

  for (const category of FEATURE_CATEGORIES) {
    lines.push(`## ${category.name}`);
    lines.push("");
    for (const f of category.features) {
      const mark = STATUS_MARK[f.status];
      lines.push(`- [${mark}] **${f.name}** (${STATUS_LABEL[f.status]}) — ${f.description}`);
      if (f.keyFiles?.length) {
        lines.push(`  - \`${f.keyFiles.join("`, `")}\``);
      }
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

const here = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(here, "..", "FEATURES.md");
writeFileSync(outPath, render(), "utf8");
console.log(`Wrote ${outPath}`);
